cloud:
  aws:
    s3:
      bucket: ''
    credentials:
      accessKey: ''
      secretKey: ''
    stack:
      auto: ''
    region:
      static: ''
springdoc:
  swagger-ui:
    path: ''
spring:
  datasource:
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ''
    url: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ''
        show_sql: ''

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
jwt:
  secret:
    key: ''

